"""High-level user interface and training recorder for ATLAS."""

from __future__ import annotations

import dataclasses
import json
import os
import pathlib
import time
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple
import numpy as np
import jax
import jax.numpy as jnp

from .basis import SubspaceBasis, trajectory_pca, compute_subspace_capture_ratio
from .certify import Certificate, certify_reconstruction
from .design import BudgetAllocator, OptimalAllocation, generate_dense_grid, generate_halton_anchors
from .device import flatten_params, unflatten_params
from .diagnostics import LandscapeDiagnostics, TrajectoryDiagnostic, SharpnessComparison
from .probe import CostModel, Jet, JetProbe
from .reconstruct import HermiteTaylorReconstruction, SurfaceAnalysis
from .viz import (
    create_landscape_gif,
    render_certificate_plot,
    render_landscape_2d,
    render_landscape_3d,
    render_sharpness_comparison_plot,
)

@dataclasses.dataclass
class RenderReport:
    """Consolidated telemetry and artifacts generated by ATLAS rendering."""
    figure_2d: str
    figure_3d: str
    animation: Optional[str]
    certificate_plot: str
    certificate: Dict[str, Any]
    allocation: Dict[str, Any]
    analysis: Dict[str, Any]
    cost_model: Dict[str, Any]
    budget_seconds: float
    elapsed_seconds: float

    def to_dict(self) -> Dict[str, Any]:
        return dataclasses.asdict(self)

    def summary(self) -> str:
        c = self.certificate
        a = self.allocation
        return (
            f"[ATLAS Report] Budget: {self.budget_seconds:.1f}s (Spent: {self.elapsed_seconds:.2f}s)\n"
            f"Anchors: {a['n_est']} estimation + {a['n_cert']} certification (Batch size: {a['batch_size']})\n"
            f"Accuracy: 95% of loss domain certified within +/-{c['q95_upper_bound']:.4f} "
            f"({c['relative_q95_error_pct']:.1f}% of dynamic relief)\n"
            f"Condition Number: {self.analysis['origin_condition_number']:.2f} | "
            f"Flatness Index: {self.analysis['flatness_index']:.4f}\n"
            f"Outputs: {self.figure_2d}, {self.figure_3d}, {self.animation}"
        )


class AtlasRecorder:
    """Attaches to any JAX training loop, records optimizer trajectory, and produces certified landscapes."""

    def __init__(
        self,
        apply_fn: Callable[[Any, Any], jnp.ndarray],
        loss_fn: Callable[[jnp.ndarray, Any], jnp.ndarray],
        eval_batches: Sequence[Any],
        every: int = 50,
        max_snapshots: int = 100
    ):
        self.apply_fn = apply_fn
        self.loss_fn = loss_fn
        self.eval_batches = eval_batches
        self.every = every
        self.max_snapshots = max_snapshots

        self._snapshots: List[jnp.ndarray] = []
        self._grads: List[jnp.ndarray] = []
        self._losses: List[float] = []
        self._step_counter = 0
        self._meta: Any = None

    @property
    def snapshots(self) -> List[np.ndarray]:
        return self._snapshots

    @property
    def grads(self) -> List[np.ndarray]:
        return self._grads

    @property
    def losses(self) -> List[float]:
        return self._losses

    def step(self, params: Any, grad: Optional[Any] = None, loss: Optional[float] = None) -> None:
        """Records a parameter snapshot if the step stride matches."""
        self._step_counter += 1
        if self._step_counter % self.every == 0 or len(self._snapshots) == 0:
            flat_p, meta = flatten_params(params)
            self._meta = meta
            self._snapshots.append(flat_p)
            
            if grad is not None:
                flat_g, _ = flatten_params(grad)
                self._grads.append(flat_g)
            if loss is not None:
                self._losses.append(float(loss))

            # Thin trajectory if exceeding max_snapshots to conserve host memory
            if len(self._snapshots) > self.max_snapshots:
                self._snapshots = self._snapshots[::2]
                if self._grads:
                    self._grads = self._grads[::2]
                if self._losses:
                    self._losses = self._losses[::2]
                self.every *= 2

    def render(
        self,
        output_dir: str = "atlas_output",
        budget_seconds: float = 20.0,
        resolution: int = 80,
        animate: bool = True
    ) -> RenderReport:
        """Executes budget-optimal probing, partition of unity reconstruction, certification, and rendering."""
        t_start = time.perf_counter()
        out_path = pathlib.Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        assert len(self._snapshots) >= 2, "Need at least 2 parameter snapshots to construct trajectory plane"

        # 1. Build PCA Subspace from Trajectory
        basis = trajectory_pca(self._snapshots, self._meta)
        traj_2d = np.array([basis.project_point(theta) for theta in self._snapshots])

        # 2. Determine Bounding Domain Radius
        rx = float(max(np.max(np.abs(traj_2d[:, 0])) * 1.3, 0.5))
        ry = float(max(np.max(np.abs(traj_2d[:, 1])) * 1.3, 0.5))
        radius = float(np.sqrt(rx ** 2 + ry ** 2))

        # 3. Setup TPU Jet Probe & Calibrate
        probe = JetProbe(self.apply_fn, self.loss_fn, basis)
        batch_sizes = [16, 32, 64, 128]
        cost_model = probe.calibrate(self.eval_batches, batch_sizes, radius=radius)

        # 4. Budget-Optimal Allocation Solver
        allocator = BudgetAllocator(cost_model, cert_fraction=0.18)
        allocation = allocator.solve(budget_seconds=budget_seconds, radius=radius)

        # 5. Generate Quasi-Random Anchors
        all_anchors = generate_halton_anchors(allocation.n_total, radius_x=rx, radius_y=ry)
        est_coords = all_anchors[:allocation.n_est]
        cert_coords = all_anchors[allocation.n_est:]

        # 6. Evaluate Jets on TPU
        eval_batch = self.eval_batches[0]
        est_jets = [probe.evaluate_jet(x, y, eval_batch) for x, y in est_coords]
        cert_jets = [probe.evaluate_jet(x, y, eval_batch) for x, y in cert_coords]

        # 7. Hermite-Taylor Partition of Unity Reconstruction
        recon = HermiteTaylorReconstruction(est_jets)
        grid_X, grid_Y, query_pts = generate_dense_grid(radius_x=rx, radius_y=ry, resolution=resolution)
        Z = recon.evaluate_batch(query_pts).reshape(grid_X.shape)

        # 8. Analytical Surface Geometry
        analysis = recon.analyze_geometry(grid_X, grid_Y)

        # 9. Statistical Error Certification
        certificate = certify_reconstruction(
            reconstruction=recon,
            cert_jets=cert_jets,
            surface_relief=analysis.surface_relief,
            confidence_level=0.95
        )

        # 10. Publication Renderings
        fig2d_path = str(out_path / "landscape_2d.png")
        fig3d_path = str(out_path / "landscape_3d.png")
        cert_plot_path = str(out_path / "certificate_plot.png")
        gif_path = str(out_path / "trajectory_evolution.gif") if animate else None

        render_landscape_2d(
            X=grid_X, Y=grid_Y, Z=Z,
            trajectory_2d=traj_2d,
            anchors=est_coords,
            cert_points=cert_coords,
            analysis=analysis,
            certificate=certificate,
            title=f"ATLAS Certified Loss Landscape (ViT/Transformer)",
            save_path=fig2d_path
        )

        render_landscape_3d(
            X=grid_X, Y=grid_Y, Z=Z,
            trajectory_2d=traj_2d,
            title="ATLAS 3D Reconstructed Loss Surface",
            save_path=fig3d_path
        )

        residuals = np.abs(recon.evaluate_batch(cert_coords) - np.array([j.loss for j in cert_jets]))
        render_certificate_plot(residuals=residuals, certificate=certificate, save_path=cert_plot_path)

        if animate:
            create_landscape_gif(
                X=grid_X, Y=grid_Y, Z=Z,
                trajectory_2d=traj_2d,
                output_path=gif_path,
                fps=6,
                title_prefix="Optimization Trajectory Evolution"
            )

        elapsed = time.perf_counter() - t_start

        report = RenderReport(
            figure_2d=fig2d_path,
            figure_3d=fig3d_path,
            animation=gif_path,
            certificate_plot=cert_plot_path,
            certificate=certificate.to_dict(),
            allocation=allocation.to_dict(),
            analysis=analysis.to_dict(),
            cost_model=cost_model.to_dict(),
            budget_seconds=budget_seconds,
            elapsed_seconds=elapsed
        )

        # Save report JSON
        with open(out_path / "atlas_report.json", "w") as f:
            json.dump(report.to_dict(), f, indent=2)

        return report
